name: vocaject_remake_v1
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.1.5 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  dotlottie_loader: ^0.0.3
  dropdown_search: ^5.0.6
  file_picker: 5.3.3
  flutter:
    sdk: flutter
  get: 4.6.6
  get_storage: 2.1.1
  google_fonts: ^6.1.0
  http: ^1.1.1
  intl: 0.18.1
  json_annotation: ^4.8.1
  lottie: ^3.0.0
  percent_indicator: ^4.2.3
  shimmer: ^3.0.0

dev_dependencies:
  build_runner: ^2.3.3
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.6.0

flutter:
  assets:
    - assets/image/
    - assets/animation/
  uses-material-design: true
